### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by stunslave** [Arkarr/SM-Super-Paypal-Donation#2]
PHP Error, when selecting/trying to buy package.
```
PHP Fatal error:  Uncaught Error: Class 'Vikas5914\SteamAuth' not found in /home/zasurfco/phatboi/donate/prepare_payment.php:9
Stack trace:
#0 {main}
  thrown in /home/zasurfco/phatboi/donate/prepare_payment.php on line 9
```

**Comment by Arkarr** [comment]
You haven't properly downloaded the package from Github. Once you have downloaded everything, check by hand that all the folders are there.

**Comment by stunslave** [comment]
Everything is there, it's broken downloaded and retested multiple times. I gave up and moved on to another plugin that works.

**Comment by Arkarr** [comment]
Well, it clearly works, since the test web site is up and running.
Too bad for you I guess. Good you have found another working solution.
