### ISSUE TITLE
Need some help making group flags apply to donator immediately (during round)

### ISSUE THREAD

**Issue by Samg381** [Arkarr/SM-Super-Paypal-Donation#4]
Hello, thank you for your work on this plugin.

I have modified it a bit in order to work with my database. I am able to detect donations and update the `admins_simple.ini` file, however I can't seem to get the part of the code working (`SetFlag` and `SetUserAdmin`) that temporarily grants the client the flags to the donator group.

[I have documented my issue on this AlliedMods thread.](https://forums.alliedmods.net/showthread.php?p=2805243#post2805243)

If you could shed any light on how you got this to function, that would be enormously helpful.

**Comment by Arkarr** [comment]
https://forums.alliedmods.net/showthread.php?p=2805243
